# Generated by Django 5.1 on 2024-08-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acessDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acessdb',
            old_name='casting',
            new_name='Casting',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='delivery',
            new_name='Delivery',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='do',
            new_name='Do',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='e_tag',
            new_name='E_tag',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='element',
            new_name='Element',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='erection',
            new_name='Erection',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='first_ir',
            new_name='First_ir',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='ir_app',
            new_name='Ir_app',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='issue',
            new_name='Issue',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='mix',
            new_name='Mix',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='p_no',
            new_name='P_no',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='pa',
            new_name='Pa',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='qc',
            new_name='Qc',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='qty',
            new_name='Qty',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='rev',
            new_name='Rev',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='second_app',
            new_name='Second_app',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='second_ir',
            new_name='Second_ir',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='tr_no',
            new_name='Tr_no',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='transporter',
            new_name='Transporter',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='vol',
            new_name='Vol',
        ),
    ]
