# Generated by Django 5.1 on 2024-08-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acessDB', '0002_rename_casting_acessdb_casting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acessdb',
            old_name='Casting',
            new_name='casting',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Delivery',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Do',
            new_name='do',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='E_tag',
            new_name='e_tag',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Element',
            new_name='element',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Erection',
            new_name='erection',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='First_ir',
            new_name='first_ir',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Ir_app',
            new_name='ir_app',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Issue',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Mix',
            new_name='mix',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='P_no',
            new_name='p_no',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Pa',
            new_name='pa',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Qc',
            new_name='qc',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Qty',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Rev',
            new_name='rev',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Second_app',
            new_name='second_app',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Second_ir',
            new_name='second_ir',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Tr_no',
            new_name='tr_no',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Transporter',
            new_name='transporter',
        ),
        migrations.RenameField(
            model_name='acessdb',
            old_name='Vol',
            new_name='vol',
        ),
    ]
