# Generated by Django 5.1 on 2024-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessDB', '0003_rename_casting_acessdb_casting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmittalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_no', models.IntegerField()),
                ('e_tag', models.CharField(max_length=255)),
                ('rev', models.IntegerField()),
                ('issue', models.DateField()),
                ('vol', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('casting', models.CharField(max_length=255)),
            ],
        ),
    ]
