# Generated by Django 5.1 on 2024-09-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessDB', '0004_transmittalform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmittalform',
            name='casting',
            field=models.CharField(max_length=255, verbose_name='Casting Factory'),
        ),
        migrations.AlterField(
            model_name='transmittalform',
            name='e_tag',
            field=models.CharField(max_length=255, verbose_name='Element Tag'),
        ),
        migrations.AlterField(
            model_name='transmittalform',
            name='issue',
            field=models.DateField(verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='transmittalform',
            name='p_no',
            field=models.IntegerField(verbose_name='Project Number'),
        ),
        migrations.AlterField(
            model_name='transmittalform',
            name='qty',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='transmittalform',
            name='rev',
            field=models.IntegerField(verbose_name='Revision'),
        ),
        migrations.AlterField(
            model_name='transmittalform',
            name='vol',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume'),
        ),
    ]
