# Generated by Django 5.1 on 2024-09-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acessDB', '0005_alter_transmittalform_casting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransmittalForm',
        ),
    ]
