# Generated by Django 5.1 on 2024-09-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessDB', '0006_delete_transmittalform'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('endpoint_url', models.URLField()),
            ],
        ),
    ]
