# Generated by Django 5.1 on 2024-09-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acessDB', '0007_registeredapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredAPI',
        ),
    ]
