# Generated by Django 5.1 on 2024-08-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModelName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_no', models.IntegerField()),
                ('e_tag', models.CharField(max_length=255)),
                ('rev', models.IntegerField()),
                ('issue', models.DateField()),
                ('vol', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('element', models.IntegerField()),
                ('casting', models.DateField()),
                ('mix', models.CharField(max_length=255)),
                ('do', models.IntegerField()),
                ('transporter', models.CharField(max_length=255)),
                ('qc', models.IntegerField()),
                ('delivery', models.DateField()),
                ('erection', models.DateField()),
                ('first_ir', models.IntegerField()),
                ('ir_app', models.IntegerField()),
                ('second_ir', models.IntegerField()),
                ('second_app', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('tr_no', models.IntegerField()),
            ],
        ),
    ]
