# Generated by Django 5.1 on 2024-08-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_yourmodelname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModelName',
        ),
    ]
